version: '3.8'

services:
  db:
    image: postgres:15
    container_name: contest_db
    restart: always
    environment:
      POSTGRES_DB: contest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contest-net

  backend:
    build: .
    container_name: contest_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contest_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "{baseUrl}/login/oauth2/code/{registrationId}"
    networks:
      - contest-net

  frontend:
    build: ./frontend
    container_name: contest_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - contest-net

  cpp-runner-builder:
    build: ./cpp-runner
    image: my-cpp-runner:latest
    container_name: contest_cpp_builder
    command: [ "true" ]
    networks:
      - contest-net

volumes:
  postgres_data:

networks:
  contest-net:
    driver: bridge