version: '3.8'

services:
  backend:
    build: .
    container_name: contest_backend
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DDL_AUTO}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "${APP_FRONTEND_URL}/login/oauth2/code/google"
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
      SHOW_SQL: ${SHOW_SQL}
    networks:
      - contest-net

  frontend:
    build:
      context: ./frontend
    container_name: contest_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - contest-net

networks:
  contest-net:
    driver: bridge
